[from-domophone]
exten => 1001,1,NoOp(Intercom incoming)
 same => n,Ringing()
 same => n,Stasis(intercom)
 same => n,Hangup()

exten => busy,1,NoOp(Busy - user rejected)
 same => n,Playback(ru/number-not-answering&ru/pls-try-call-later&ru/goodbye)
 same => n,Wait(1)
 same => n,Hangup()

exten => noanswer,1,NoOp(No answer - timeout)
 same => n,Playback(ru/vm-nobodyavail&ru/pls-try-call-later&ru/goodbye)
 same => n,Wait(1)
 same => n,Hangup()
