[Definition]
failregex =
  ^.*\[AUTH_VERIFY_WRONG_CODE\].*ip=<HOST>\b.*$
  ^.*\[AUTH_VERIFY_EXPIRED\].*ip=<HOST>\b.*$
  ^.*\[AUTH_VERIFY_INVALID\].*ip=<HOST>\b.*$
  ^.*\[AUTH_VERIFY_RATE_LIMITED\].*ip=<HOST>\b.*$
ignoreregex =
