[Definition]
failregex =
  ^.*\[AUTH_REQ_ACCEPTED\].*ip=<HOST>\b.*$
  ^.*\[AUTH_REQ_QUEUED\].*ip=<HOST>\b.*$
  ^.*\[AUTH_REQ_INVALID\].*ip=<HOST>\b.*$
  ^.*\[AUTH_REQ_RATE_LIMITED\].*ip=<HOST>\b.*$
ignoreregex =
